# Generated by Django 4.2.26 on 2025-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_delete',
            field=models.CharField(default='N', max_length=5),
        ),
    ]
