# Generated by Django 4.2.26 on 2025-11-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_ecom_app', '0003_student_image_student_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='linkedin',
        ),
    ]
