# Generated by Django 4.2.26 on 2025-11-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_ecom_app', '0004_remove_student_image_remove_student_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
